# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_region <- function(region) {
    .Call(`_raer_get_region`, region)
}

cread_tabix <- function(tbxpath, region = ".") {
    .Call(`_raer_cread_tabix`, tbxpath, region)
}

list_tabix_chroms <- function(tbxpath) {
    .Call(`_raer_list_tabix_chroms`, tbxpath)
}

c_build_index <- function(bampath, idxpath, tag) {
    .Call(`_raer_c_build_index`, bampath, idxpath, tag)
}

fetch_cb_reads <- function(bampath, outpath, cbs) {
    .Call(`_raer_fetch_cb_reads`, bampath, outpath, cbs)
}

c_show_index <- function(bamfn, idxfn) {
    .Call(`_raer_c_show_index`, bamfn, idxfn)
}

cpp_fill_sparse_matrix <- function(vals, hits) {
    .Call(`_raer_cpp_fill_sparse_matrix`, vals, hits)
}

