# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_bam_tags <- function(bampath, tag_ids, tag_types, region = ".") {
    .Call(`_raer_read_bam_tags`, bampath, tag_ids, tag_types, region)
}

read_bam <- function(bampath, tag_ids, tag_types, region = ".") {
    .Call(`_raer_read_bam`, bampath, tag_ids, tag_types, region)
}

run_pileup <- function(bampaths, fapath, region, outfn, bedfn, min_reads, event_filters, max_depth = 10000L, min_baseQ = 20L, min_mapQ = 0L, libtype = "fr-first-strand", required_flags = "0", filter_flags = "0", n_align = 1L, n_align_tag = "NH", ext = NULL) {
    .Call(`_raer_run_pileup`, bampaths, fapath, region, outfn, bedfn, min_reads, event_filters, max_depth, min_baseQ, min_mapQ, libtype, required_flags, filter_flags, n_align, n_align_tag, ext)
}

get_region <- function(region) {
    .Call(`_raer_get_region`, region)
}

c_build_index <- function(bampath, idxpath) {
    .Call(`_raer_c_build_index`, bampath, idxpath)
}

fetch_cb_reads <- function(bampath, outpath, cbs) {
    .Call(`_raer_fetch_cb_reads`, bampath, outpath, cbs)
}

